LoadCPlugin ("freesub.dll")


#AviSource ("Colorbars.avi")
ColorBars ()
AssumeFps (30, 1)
Trim (0, 299)
KillAudio ()

ConvertToRGB24 ()

#Info ()




#FreeSub ("Chicken\\naa\\aaa\nEifrrr", font="font\8x13.bdf", size=2, font_width=2, align=8, y=0, text_color = $20ffffff, halo_color=$20101000, halo_width = 1, halo_height = 1)

#FreeSub (font="penif.bdf")

FreeSub (font="font\4x6.bdf", y=10)
FreeSub (font="font\5x7.bdf", y=25)
FreeSub (font="font\5x8.bdf", y=40)
FreeSub (font="font\6x9.bdf", y=50)
FreeSub (font="font\6x10.bdf", y=60)
FreeSub (font="font\6x12.bdf", y=75)
FreeSub (font="font\6x13.bdf", y=90)
FreeSub (font="font\6x13B.bdf", y=105)
FreeSub (font="font\7x13.bdf", y=120)
FreeSub (font="font\7x13B.bdf", y=135)
FreeSub (font="font\7x13O.bdf", y=150)
FreeSub (font="font\7x14.bdf", y=165)
#FreeSub (font="font\7x14O.bdf", y=180)
FreeSub (font="font\8x13.bdf", y=195)
FreeSub (font="font\8x13B.bdf", y=210)
FreeSub (font="font\8x13O.bdf", y=225)
FreeSub (font="font\9x15.bdf", y=240)
FreeSub (font="font\9x15B.bdf", y=255)
FreeSub (font="font\9x18.bdf", y=270)
FreeSub (font="font\9x18B.bdf", y=285)
FreeSub (font="font\10x20.bdf", y=300)
FreeSub (font="font\clR6x12.bdf", y=315)
FreeSub (font="font\helvR12.bdf", y=330)

